### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by curioustechizen** [senseobservationsystems/back-off-android#1]
- [ ] AlarmManager APIs
  - [ ] Wake up the app using Geofencing
  - [ ] Wake up the app on user activity
  - [ ] Wake up the app on WiFi status changes
  - [ ] Wake up the app on Power charging status changes
